CREATE TABLE IF NOT EXISTS historico_impressoras (
    id INT(11) NOT NULL AUTO_INCREMENT,
    impressora_id INT(11) NOT NULL,
    data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paginas_total INT(11) DEFAULT NULL,
    paginas_pb INT(11) DEFAULT NULL,
    paginas_cor INT(11) DEFAULT NULL,
    a4_pb_simples INT(11) DEFAULT NULL,
    a4_cor_simples INT(11) DEFAULT NULL,
    a4_pb_duplex INT(11) DEFAULT NULL,
    a4_cor_duplex INT(11) DEFAULT NULL,
    a3_pb_simples INT(11) DEFAULT NULL,
    a3_cor_simples INT(11) DEFAULT NULL,
    a3_pb_duplex INT(11) DEFAULT NULL,
    a3_cor_duplex INT(11) DEFAULT NULL,
    tinta_preto VARCHAR(20) DEFAULT NULL,
    tinta_ciano VARCHAR(20) DEFAULT NULL,
    tinta_magenta VARCHAR(20) DEFAULT NULL,
    tinta_amarelo VARCHAR(20) DEFAULT NULL,
    status_impressora VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY fk_historico_impressora (impressora_id),
    CONSTRAINT fk_historico_impressora FOREIGN KEY (impressora_id) REFERENCES impressoras (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
